version: "3"

services:
  db.track_xpress:
    container_name: db_track_xpress
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=track_xpress_db
      - POSTGRES_USER=track_xpress_user
      - POSTGRES_PASSWORD=track_xpress_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./.tmp/psgdb:/var/lib/postgresql@14/data


  app.track_xpress:
    container_name: app_track_xpress
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - /app/libnew
    ports:
      - 5050:5050
    environment:
      DOCKER_FLAG: "true"
      POSTGRES_URL: db.track_xpress
      CONTAINER_ENV: localhost
    depends_on:
      - db.track_xpress

  client:
    build: client
    command: [ "npm", "start" ]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - app.track_xpress

volumes:
  node-modules: